### ISSUE TITLE
why compose Java and Bitboard

### ISSUE THREAD

**Issue by hotfics** [sandermvdb/chess22k#1]
BitBord is suitable for bit operation,it efficient in lowe level language such as C,thats the good part,the bad part is  it hard to read for human.I dont quite understand the composition you choose.

**Comment by sandermvdb** [comment]
I wrote the engine in Java because I knew that language and I liked it.
My engine had to be fast so therefore I used bitboards. And to be honest, after a while bitboards are not that hard to read anymore.
