### ISSUE TITLE
start chess22k ?

### ISSUE THREAD

**Issue by tissatussa** [sandermvdb/chess22k#13]
i did a git clone but how to start chess22k ?  The README states "The binary is build using Java 14. Also a Java 11 binary is supplied." but i see no binary .. how to build it ?  I'm on Xubuntu 20.04

**Comment by sandermvdb** [comment]
If you download the source and have Java and Maven installed, you can execute the following command to create the binary (chess22k.jar) yourself:
mvn clean install

You can also download this binary (.jar-file) from Github from the releases section. This section contains 2 jar files, one compiled using Java 11, the other using Java 14.

Hope this helps.
