### ISSUE TITLE
Which JAVA to use...

### ISSUE THREAD

**Issue by SLW2K** [sandermvdb/chess22k#14]
I am using Windows 7 64-Bit - do I use version 11 or higher from this site?

https://www.oracle.com/java/technologies/javase/jdk17-archive-downloads.html

Shawn Weber

**Comment by sandermvdb** [comment]
I've compiled 2 binaries (.jar-files) which can be downloaded from the releases page.
One is compiled using java 11, the other using java 15.
Java is backwards compatible so if you download the latest version (17) you can run both.

**Comment by SLW2K** [comment]
Would you be willing to compile a version for Java 8? I'm asking because it's the current version for Windows 7 & 10; otherwise I have to install 400+MB of Java 17. I hope I don't sound like a jerk.

**Comment by SLW2K** [comment]
Jesus Christ, I guess some people ask too much of others - most people would like to be able to download and run a program, not have to go download and install *additional* software. No reply either, man excuse me for asking.
