### ISSUE TITLE
King blocked at last rank

### ISSUE THREAD

**Issue by ratosh** [sandermvdb/chess22k#2]
It seems that it does not consider enemy attacks. Tested on this board:
`6k1/4rp1p/6pP/3p2P1/5P2/3bP1K1/1q6/2R5 w - -`

**Comment by sandermvdb** [comment]
Thanks for raising this issue 👍 
I've updated the code which will be part of the 1.8 release:

```java
private static boolean kingBlockedAtLastRank(final int kingIndex, final int kingColor, final ChessBoard cb) {
    return cb.colorToMove != kingColor && (Bitboard.RANKS[7 * kingColor] & cb.pieces[kingColor][KING]) != 0 
      && (StaticMoves.KING_MOVES[kingIndex] & cb.emptySpaces & ~cb.attacksAll[1 - kingColor] & Bitboard.RANKS[7 * kingColor]) 
      == (StaticMoves.KING_MOVES[kingIndex] & cb.emptySpaces & ~cb.attacksAll[1 - kingColor]);
}
```

**Comment by ratosh** [comment]
Still a small problem when moving a rook or a queen from rank6 to rank7. attacksAll will have attacks to rank6 and this function when detecting safe rook checks will return the king is blocked.
`3k4/7R/8/8/8/8/8/7K w - -`

**Comment by sandermvdb** [comment]
Performance vs accuracy...
