### ISSUE TITLE
Chess22k 1.8 under Windows 10

### ISSUE THREAD

**Issue by gpaunica** [sandermvdb/chess22k#4]
Hello,
This engine works in Windows 10?
If it works, please tell me what else should I do besides install Oracle Java 9?
After I installed Oracle Java 9 and double click on the engine, nothing happens.
And when I try to install in a GUI, the GUI asks for .exe files.
Thanks a lot.

**Comment by sandermvdb** [comment]
This engine does work in Windows 10 (and Linux, and MacOS, that is the beauty of java :) )

With Arena 3.5.1 you can just select the .jar file in the commandline (and select UCI as engine type).
If you have to specify a .exe file, you can use the following syntax:
java -jar [location-of-jar]

For instance:
java -jar c:\chess22k-1.8.jar

This works just fine in CuteChess GUI.

**Comment by kostuek** [comment]
To test in console mode, you can create a text file in the same directory with
`java -jar c:\chess22k-1.8.jar`
`pause`
as content. Then rename this text file to .bat
Now you can double click the .bat file and see if it shows any errors. If not, you can test the engine response by typing in 
uci

**Comment by khuttur** [comment]
Would you make an android version of it?
Thanks
