### ISSUE TITLE
PawnEvalCache key

### ISSUE THREAD

**Issue by ratosh** [sandermvdb/chess22k#6]
It seems that pawn evaluation is using king position in evaluation but the board pawnZobristKey does not consider king position, it may lead to getting wrong evaluation values from cache.

**Comment by sandermvdb** [comment]
Where do you see that the king position is being used (linenumber)? I cannot find it...
I agree that it is being used in the PassedPawnEval but that score is not cached.
Maybe I will add the pawn-shield score to the pawn cache and then I will add the king position to the cache key. But this will have a negative impact on the hit rate so I don't know if this is a good idea.

**Comment by ratosh** [comment]
You're right, i saw king position  being used indirectly by the function calculatePassedPawnScores -> getPassedPawnScore but indeed it is not being cached. Would be worth to create a kingPawnZobristKey to cache this function value?

**Comment by sandermvdb** [comment]
The calculation of the pawn-king-tropism within getPassedPawnScore() could indeed be added to a cache which also uses the king-position within the key. Same applies for the calculation of the pawn-shield score. But as I said, I don't know if the cache hit rate would be high enough to have a positive impact.
