### ISSUE TITLE
Chess22k 1.12 doesn't works

### ISSUE THREAD

**Issue by gpaunica** [sandermvdb/chess22k#7]
Hello Mr.,
I tried to install Chess22k 1.12 in Arena 3.5.1, but doesn't work/ Whent I try to change the engine properties it apears nothing. Also it doesn't move at all.
Chess22k 1.11 it works fine.
I have Java 10.0.2 installed.
Thanks.

**Comment by sandermvdb** [comment]
The binary (jar-file) that is included in the 1.12 release is compiled using Java 11. Please install Oracle JDK 11 or OpenJDK 11.

**Comment by gpaunica** [comment]
Thanks for your answer Mr.,
I installed Java 11.0.1, and now I receive the error:
Java not in the Path variable
The engine could not start
Please help me.
Thanks a lot.
